import type { Metadata } from "next";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import Footer from "@/components/Footer";
import MobileNavbar from "@/components/MobileNavbar";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="no-scroll">
      <body className="bg:-[#FBFBFB] dark:bg-black">
        <Providers>
          <Image
            src="/BG_Dark.svg"
            alt="alt"
            width={300}
            height={300}
            className="absolute top-0 -z-10 w-full h-[280px] object-cover object-center"
          />
          <div className="max-w-screen flex justify-center">
            <Navbar />
          </div>
          <MobileNavbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
