export const cards = [
  {
    src: "/React.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[100px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "React Js",
    category: "Frontend",
  },

  {
    src: "/Nextjs.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[100px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "Next Js",
    category: "React Framework",
  },
  {
    src: "/Redux.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[85px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "Redux",
    category: "State Management",
  },

  {
    src: "/TailwindCSS.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[100px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "Tailwind CSS",
    category: "CSS",
  },
  {
    src: "/Figma.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[100px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "Figma",
    category: "Design",
  },
  {
    src: "/GithubTech.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[100px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "GitHub",
    category: "Version Control",
  },
  {
    src: "/Vercel.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[100px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "Vercel",
    category: "Deployment",
  },
  {
    src: "/VSCode.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[100px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "VSCode",
    category: "Editor",
  },
  {
    src: "/Framer.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[100px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "Framer Motion",
    category: "Animation",
  },
  {
    src: "/Netlify.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[85px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "Netlify",
    category: "Deployment",
  },
  // Done
  {
    src: "/HTML.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[85px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "HTML 5",
    category: "Web Dev",
  },
  {
    src: "/PSQL.svg",
    alt: "alt",
    width: 200,
    height: 200,
    className: "w-[85px] mt-24 2xl:w-[114px] 2xl:mt-20 hidden md:block",
    title: "PostgreSQL",
    category: "Database",
  },
];
